In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.linear_model import LinearRegression
import warnings


warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df = pd.read_csv('/content/drive/MyDrive/kream_data/product_data_dpp.csv')
df.head(3)

product_id                                   img_path brand  \
0      28029  crawling\product_crawling\image\28029.jpg  Nike   
1      12831  crawling\product_crawling\image\12831.jpg  Nike   
2      21935  crawling\product_crawling\image\21935.jpg  Nike   

                             name color1 color2  price_og  price_resell  \
0       Nike Dunk Low Retro Black  WHITE  BLACK    129000        152800   
1  Nike Air Force 1 '07 Low White  WHITE  WHITE    139000        136200   
2    Nike Air Force 1 '07 WB Flax   FLAX    GUM    169000        173200   

    n_scrap  +price                              tokenized_color  \
0  123000.0   23800                [0 0 0 0 0 0 0 0 0 0 2 4 3 5]   
1  151000.0   -2800                [0 0 0 0 0 0 0 0 0 0 2 4 3 4]   
2   69000.0    4200  [ 0  0  0  0  0  0  0  0  0  0  2 82  3 51]   

                                        tokenized_bn  
0  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  2  4 ...  
1  [ 0  0  0  0  0  0  0  0  0  0  0  2  4  3  4 ...  
2  [   0    0    0    0    0    0    0    0    0 ...

In [4]:
df.shape

(6103, 12)

https://swlock.blogspot.com/2019/04/keras-lstm-understanding-input-and.html

링크를 참조함.

In [5]:
bn_input_data = np.array([])

for val in df['tokenized_bn'].values:
    val = [int(x) for x in val.strip('[]').split()]
    bn_input_data = np.append(bn_input_data, val)

bn_input_data = bn_input_data.reshape([6103, 21])

In [6]:
bn_input_data.shape

(6103, 21)

In [7]:
bn_input_data

array([[   0.,    0.,    0., ...,   14.,   15.,   10.],
       [   0.,    0.,    0., ...,   42.,   14.,   11.],
       [   0.,    0.,    0., ...,   42., 1100.,  399.],
       ...,
       [   0.,    0.,    0., ...,  740.,   31.,   10.],
       [   0.,    0.,    0., ...,  263.,   31.,   11.],
       [   0.,    0.,    0., ...,  740.,   31.,   11.]])

In [8]:
target_data = np.array(df['+price'])
print(target_data.shape)

(6103,)


In [9]:
target_data

array([ 23800,  -2800,   4200, ..., 115600, 144000,  86500])

input data의 크기는 
(6103, 21) 이다.

In [10]:
np.random.seed(42)
tf.random.set_seed(42)

bn_model = keras.models.Sequential([
    keras.layers.Dense(21),
    keras.layers.Dense(10),
    keras.layers.Dense(5),
    keras.layers.Dense(1)    
])

bn_model.compile(loss="mse")
history = bn_model.fit(bn_input_data, target_data, epochs=20)

Epoch 1/20
191/191 [==============================] - 1s 2ms/step - loss: 94255185920.0000
Epoch 2/20
191/191 [==============================] - 0s 2ms/step - loss: 93900038144.0000
Epoch 3/20
191/191 [==============================] - 0s 2ms/step - loss: 93291798528.0000
Epoch 4/20
191/191 [==============================] - 0s 2ms/step - loss: 92857237504.0000
Epoch 5/20
191/191 [==============================] - 0s 2ms/step - loss: 92682133504.0000
Epoch 6/20
191/191 [==============================] - 0s 2ms/step - loss: 92619161600.0000
Epoch 7/20
191/191 [==============================] - 0s 2ms/step - loss: 92522602496.0000
Epoch 8/20
191/191 [==============================] - 0s 2ms/step - loss: 92466692096.0000
Epoch 9/20
191/191 [==============================] - 0s 2ms/step - loss: 92499058688.0000
Epoch 10/20
191/191 [==============================] - 0s 2ms/step - loss: 92430106624.0000
Epoch 11/20
191/191 [==============================] - 0s 2ms/step - loss: 92408037376.00

In [11]:
bn_model.predict(bn_input_data[0].reshape(1,21))

1/1 [==============================] - 0s 107ms/step


array([[816.1173]], dtype=float32)

In [12]:
bn_input_data[0].reshape(1,21).shape

(1, 21)

In [19]:
, sqrt
# create and fit the model
reg = LinearRegression().fit(bn_input_data, target_data)

# make predictions using the model
predictions = reg.predict(bn_input_data)

# print the prediction
print("mse:", sum(abs((predictions-target_data)))/6013)

mse: 120958.66920233499
